name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Set Yarn Berry
        run: corepack enable && corepack prepare yarn@3.6.4 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: TypeScript Type Check
        run: yarn exec tsc --noEmit --pretty

      - name: Lint Code
        run: yarn lint

      - name: Check Code Formatting
        run: yarn format:check

      - name: Run Tests
        run: yarn test:ci

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  functions:
    name: Functions Build and Lint
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Yarn Berry
        run: corepack enable && corepack prepare yarn@3.6.4 --activate

      - name: Install Dependencies
        run: |
          cd functions
          yarn install --immutable

      - name: Lint
        run: |
          cd functions
          yarn lint

      - name: Build
        run: |
          cd functions
          yarn build
